# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBasictest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='/Users/jameel/aatemp/rajesh/chromedriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_basictest(self):
    self.driver.get("http://localhost:8012/")
    self.driver.set_window_size(728, 483)
    self.driver.find_element(By.NAME, "unit_input").click()
    self.driver.find_element(By.NAME, "unit_input").send_keys("84.2")
    self.driver.find_element(By.NAME, "unit_menu").click()
    dropdown = self.driver.find_element(By.NAME, "unit_menu")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Fahrenheit (\'F)']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").send_keys("543.94")
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Rankine (\'R)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.NAME, "unit_input").click()
    self.driver.find_element(By.NAME, "unit_input").send_keys("317.33")
    self.driver.find_element(By.NAME, "unit_menu").click()
    dropdown = self.driver.find_element(By.NAME, "unit_menu")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Kelvin (\'K)']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").send_keys("111.554")
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Fahrenheit (\'F)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.NAME, "unit_input").click()
    self.driver.find_element(By.NAME, "unit_input").send_keys("6.5")
    self.driver.find_element(By.NAME, "unit_menu").click()
    dropdown = self.driver.find_element(By.NAME, "unit_menu")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Fahrenheit (\'F)']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").send_keys("dog")
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Rankine (\'R)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.NAME, "unit_input").click()
    self.driver.find_element(By.NAME, "unit_input").send_keys("136.1")
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").click()
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b .numbersonly").send_keys("45.32")
    self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".converter-side-b select")
    dropdown.find_element(By.XPATH, "//option[. = 'Degrees Celsius (\'C)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
obj=TestBasictest()
obj.setup_method('')

obj.test_basictest()
